name: apidocs
on:
- push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # Unreleased (yet) version of pydoctor that supports --docformat=google
        python -m pip install docutils git+https://github.com/tristanlatr/pydoctor.git@08baf17220902770f0d67906501da6cf300d74de

    - name: Generate googleapiclient documentation with pydoctor
      run: |

        # Run pydoctor build
        pydoctor \
            --project-name="Google API Python Client" \
            --project-url=https://github.com/$GITHUB_REPOSITORY \
            --html-viewsource-base=https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --make-html \
            --html-output=./apidocs \
            --project-base-dir="$(pwd)" \
            --docformat=google \
            --intersphinx=https://docs.python.org/3/objects.inv \
            ./googleapiclient || true

    - name: Publish pydoctor documentation to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate API documentation"
